language: python

python:
  - "2.7"

env:
  - NUODB_VERSION=2.0.4
  - NUODB_VERSION=2.0.3
  - NUODB_VERSION=2.0.2
  - NUODB_VERSION=2.0.1
  - NUODB_VERSION=2.0

notifications:
  recipients:
    - buck.robert.j@gmail.com
    - rbuck@nuodb.com
    - jgetto@nuodb.com
    - tgates@nuodb.com

before_install:
  - wget http://download.nuohub.org/nuodb-${NUODB_VERSION}.linux.x64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 4
  
script:
  - make all

after_failure:
  - cat /var/log/nuodb/agent.log
