language: python

python:
  - "2.7"

env:
  - NUODB_VERSION=2.0
  - NUODB_VERSION=1.2

notifications:
  recipients:
    - buck.robert.j@gmail.com
    - rbuck@nuodb.com
    - jgetto@nuodb.com

before_install:
  - wget http://www.nuodb.com/latest/releases/nuodb-${NUODB_VERSION}.linux.x64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 4
  
script:
  - make all

after_script:
  - sudo dpkg -r nuodb
