language: python

python:
  - "2.7"

env:
  - NUODB_VERSION=2.1.1.10_amd64 NUODB_DOWNLOAD_URL=http://download.nuohub.org/nuodb_${NUODB_VERSION}.deb NUODB_ADD_DOMAIN_PASS=yes NUODB_START_AGENT=yes
  - NUODB_VERSION=2.0.4.24_amd64 NUODB_DOWNLOAD_URL=http://download.nuohub.org/nuodb_${NUODB_VERSION}.deb NUODB_ADD_DOMAIN_PASS=no NUODB_START_AGENT=no

notifications:
  recipients:
    - buck.robert.j@gmail.com
    - rbuck@nuodb.com
    - jgetto@nuodb.com
    - tgates@nuodb.com

before_install:
  - wget ${NUODB_DOWNLOAD_URL} --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 4
  - if [[ "${NUODB_ADD_DOMAIN_PASS}" == "yes" ]] ; then sudo chmod 777 /opt/nuodb/etc/default.properties; echo "domainPassword = bird" >> /opt/nuodb/etc/default.properties; sudo chmod 600 /opt/nuodb/etc/default.properties; fi
  - if [[ "${NUODB_START_AGENT}" == "yes" ]]; then sudo service nuoagent start; fi

  
script:
  - make all

after_failure:
  - cat /var/log/nuodb/agent.log
